on: push #Acción para activarse
name: Ejecutar tests al hacer push #Nombre de la secuencia
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar y checkout de la rama actual
        uses: actions/checkout@v1
      - name: Instalar dependencias
        run: yarn install
      - name: Ejecutando tests
        run: yarn test
